version: '3.1'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile

    links:
      - db
    ports:
      - 5000:5000
    volumes:
      - ./:/elms

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080